AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
    Default: Demo

  VpcCidr:
    Description: CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16
  
  AmiId:
    Description: Ami ID
    Type: String
    Default: ami-04376654933b081a7
    
Resources:
  VPCSubnetStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'vpc-stack.yaml'

  SecurityGroupsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'security-groups.yaml'

  EC2InstancesStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'ec2-instances.yaml'
