---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  The template is used to create RDS instance.

#
#PARAMETERS used to Create Ec2 Instances
#
Parameters:
  PrivateSecurityGroup.GroupId:
     Description: The security group
     Type: String
  DBSubnetGroup:
     Description: The db subnet group that needs to be associated with the db instance
     Type: String

#
#RESOURCES created
#
Resources:

#RDS instance
  RDSDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      DBInstanceIdentifier: MyDBInstance
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: myadmin
      MasterUserPassword: mypassword
      MultiAZ: false
      StorageType: gp2
      VPCSecurityGroups: 
        - !GetAtt PrivateSecurityGroup.GroupId
      AvailabilityZone: eu-central-1a
      DBSubnetGroupName: !Ref DBSubnetGroup

#
#OUTPUT
#
Outputs:
#RDS Instance
  RDSDBInstance:
    Description: The id of rds instance
    Value: !Ref RDSDBInstance